modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "trackertips"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"

description = '''${mod_description}'''

[[dependencies."trackertips"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."trackertips"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."trackertips"]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.1.106,12)"
ordering = "AFTER"
side = "CLIENT"
